[package]
name = "modesetting"
description = "Safe interface for DRM modesetting and display buffers"
version = "0.0.1"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]
license = "LGPL-3.0"
repository = "https://github.com/Slabity/modesetting-rs"
build = "build.rs"

[build-dependencies]
gcc = "0.3.31"
bindgen = "0.19.0"

[dependencies]
libc = "0.2.14"
errno = "0.1.7"
