[package]
name = "modesetting"
description = "Safe interface for DRM modesetting and display buffers"
version = "0.0.0"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]
license = "LGPL-3.0"
repository = "https://gitlab.com/slabity/drm-rs"
build = "build.rs"

[build-dependencies]
gcc = "*"
bindgen = "*"

[dependencies]
libc = "*"
errno = "*"
