#include <libdrm/drm.h>

// Type flags
const unsigned int FFI_DRM_MODE_TYPE_BUILTIN =      DRM_MODE_TYPE_BUILTIN;
const unsigned int FFI_DRM_MODE_TYPE_CLOCK_C =      DRM_MODE_TYPE_CLOCK_C;
const unsigned int FFI_DRM_MODE_TYPE_CRTC_C =       DRM_MODE_TYPE_CRTC_C;
const unsigned int FFI_DRM_MODE_TYPE_PREFERRED =    DRM_MODE_TYPE_PREFERRED;
const unsigned int FFI_DRM_MODE_TYPE_DEFAULT =      DRM_MODE_TYPE_DEFAULT;
const unsigned int FFI_DRM_MODE_TYPE_USERDEF =      DRM_MODE_TYPE_USERDEF;
const unsigned int FFI_DRM_MODE_TYPE_DRIVER =       DRM_MODE_TYPE_DRIVER;

// Video mode flags
const unsigned int FFI_DRM_MODE_FLAG_PHSYNC =       DRM_MODE_FLAG_PHSYNC;
const unsigned int FFI_DRM_MODE_FLAG_NHSYNC =       DRM_MODE_FLAG_NHSYNC;
const unsigned int FFI_DRM_MODE_FLAG_PVSYNC =       DRM_MODE_FLAG_PVSYNC;
const unsigned int FFI_DRM_MODE_FLAG_NVSYNC =       DRM_MODE_FLAG_NVSYNC;
const unsigned int FFI_DRM_MODE_FLAG_INTERLACE =    DRM_MODE_FLAG_INTERLACE;
const unsigned int FFI_DRM_MODE_FLAG_DBLSCAN =      DRM_MODE_FLAG_DBLSCAN;
const unsigned int FFI_DRM_MODE_FLAG_CSYNC =        DRM_MODE_FLAG_CSYNC;
const unsigned int FFI_DRM_MODE_FLAG_PCSYNC =       DRM_MODE_FLAG_PCSYNC;
const unsigned int FFI_DRM_MODE_FLAG_NCSYNC =       DRM_MODE_FLAG_NCSYNC;
const unsigned int FFI_DRM_MODE_FLAG_HSKEW =        DRM_MODE_FLAG_HSKEW;
const unsigned int FFI_DRM_MODE_FLAG_BCAST =        DRM_MODE_FLAG_BCAST;
const unsigned int FFI_DRM_MODE_FLAG_PIXMUX =       DRM_MODE_FLAG_PIXMUX;
const unsigned int FFI_DRM_MODE_FLAG_DBLCLK =       DRM_MODE_FLAG_DBLCLK;
const unsigned int FFI_DRM_MODE_FLAG_CLKDIV2 =      DRM_MODE_FLAG_CLKDIV2;

// TODO: Stereo modes here

typedef enum {
    FFI_DRM_MODE_ENCODER_NONE =      DRM_MODE_ENCODER_NONE,
    FFI_DRM_MODE_ENCODER_DAC =       DRM_MODE_ENCODER_DAC,
    FFI_DRM_MODE_ENCODER_TMDS =      DRM_MODE_ENCODER_TMDS,
    FFI_DRM_MODE_ENCODER_LVDS =      DRM_MODE_ENCODER_LVDS,
    FFI_DRM_MODE_ENCODER_TVDAC =     DRM_MODE_ENCODER_TVDAC,
    FFI_DRM_MODE_ENCODER_VIRTUAL =   DRM_MODE_ENCODER_VIRTUAL,
    FFI_DRM_MODE_ENCODER_DSI =       DRM_MODE_ENCODER_DSI,
    FFI_DRM_MODE_ENCODER_DPMST =     DRM_MODE_ENCODER_DPMST
} EncoderType;

typedef enum {
    FFI_DRM_MODE_CONNECTOR_Unknown =     DRM_MODE_CONNECTOR_Unknown,
    FFI_DRM_MODE_CONNECTOR_VGA =         DRM_MODE_CONNECTOR_VGA,
    FFI_DRM_MODE_CONNECTOR_DVII =        DRM_MODE_CONNECTOR_DVII,
    FFI_DRM_MODE_CONNECTOR_DVID =        DRM_MODE_CONNECTOR_DVID,
    FFI_DRM_MODE_CONNECTOR_DVIA =        DRM_MODE_CONNECTOR_DVIA,
    FFI_DRM_MODE_CONNECTOR_Composite =   DRM_MODE_CONNECTOR_Composite,
    FFI_DRM_MODE_CONNECTOR_SVIDEO =      DRM_MODE_CONNECTOR_SVIDEO,
    FFI_DRM_MODE_CONNECTOR_LVDS =        DRM_MODE_CONNECTOR_LVDS,
    FFI_DRM_MODE_CONNECTOR_Component =   DRM_MODE_CONNECTOR_Component,
    FFI_DRM_MODE_CONNECTOR_9PinDIN =     DRM_MODE_CONNECTOR_9PinDIN,
    FFI_DRM_MODE_CONNECTOR_DisplayPort = DRM_MODE_CONNECTOR_DisplayPort,
    FFI_DRM_MODE_CONNECTOR_HDMIA =       DRM_MODE_CONNECTOR_HDMIA,
    FFI_DRM_MODE_CONNECTOR_HDMIB =       DRM_MODE_CONNECTOR_HDMIB,
    FFI_DRM_MODE_CONNECTOR_TV =          DRM_MODE_CONNECTOR_TV,
    FFI_DRM_MODE_CONNECTOR_eDP =         DRM_MODE_CONNECTOR_eDP,
    FFI_DRM_MODE_CONNECTOR_VIRTUAL =     DRM_MODE_CONNECTOR_VIRTUAL,
    FFI_DRM_MODE_CONNECTOR_DSI =         DRM_MODE_CONNECTOR_DSI
} ConnectorInterface;

typedef enum {
    FFI_DRM_MODE_CONNECTED      = 1,
    FFI_DRM_MODE_DISCONNECTED   = 2,
    FFI_DRM_MODE_UNKNOWN        = 3
} Connection;
